### ISSUE TITLE
データベースの作成

### ISSUE THREAD

**Issue by Sut103** [EIMIKI/dropout_s_back#1]
## やること
* 事前の設計(?)に則ったテーブル定義を作成する。

## やりかた
* どっちがいいだろう
  * 案1. 単純に.sqlファイルなどで定義する。
  * 案2. GORMなど導入して定義。マイグレーションもできるようにする。

**Comment by Sut103** [comment]
GORMは使ったことが無いが、ActiveRecordみたいな物だろうと勝手に思っている。

**Comment by shokkunrf** [comment]
GORMよさげ

**Comment by Sut103** [comment]
じゃあGORM入れてみますか。

**Comment by Sut103** [comment]
GORMでデータベースを作成。マージしました。
クローズです。
