### ISSUE TITLE
packageが循環参照してしまう

### ISSUE THREAD

**Issue by Sut103** [EIMIKI/dropout_s_back#13]
## 問題点
* controllerからGORMでDBをいじろうとすると循環参照する。
* controller→db→config→controller...

## 解決策
* 案1 . dbconfig.goをdbパッケージに移動する。（または違った管理方法を導入)
* 案2 . データベース接続は各APIで個別に取得するようにしてController構造体に含めない。

**Comment by shokkunrf** [comment]
go buildのときはroute.goを参照してくれるけれど、go runのときは参照してくれない。
route/route.goとするのはどうだろう？

**Comment by Sut103** [comment]
毎回buildしてたので盲点でした...。
不便ならそのように変えてもらってダイジョブです。
