### ISSUE TITLE
ルーティングの定義

### ISSUE THREAD

**Issue by Sut103** [EIMIKI/dropout_s_back#2]
## やること
* APIのエンドポイントになるルートを定義する
  * ユーザ登録
  * メッセージ作成
  * メッセージ取得
  * BLE一覧取得

## やりかた
* 素で書くか、フレームワーク使うかによって変わる

**Comment by shokkunrf** [comment]
ginが楽そう

**Comment by Sut103** [comment]
echoも同じような雰囲気を感じた。
どっちがいいだろうか。

**Comment by Sut103** [comment]
同じならGinでいいような気がした

**Comment by Sut103** [comment]
マージしました。
クローズ。
