### ISSUE TITLE
ユーザ登録APIの作成

### ISSUE THREAD

**Issue by Sut103** [EIMIKI/dropout_s_back#3]
## やること
* ユーザ登録用のAPIをつくる

### 必要なこと
* アプリからのパラメータをデータベースに登録
  * ユーザ名
  * パスワード
  * デバイス
* 成否を返す

## やりかた
* ルーティングの先にメソッドを書いていく

**Comment by Sut103** [comment]
デバイス情報とパスワードは本当に必要なのか、今一度検討してもいい気がした。
ユーザが端末を変更することを考慮しなければ無くてもいいかもしれない？

**Comment by Sut103** [comment]
また、同名のユーザ名を認めるかについても検討するべきかもしれない。

**Comment by shokkunrf** [comment]
アカウント登録と同時にデバイス登録を行えばパスワードはなくてもいいんじゃないかってこと？

**Comment by Sut103** [comment]
んー...。そうかも？
書いたときはデバイスもいらない気がしてたけどそれはおかしいか。

**Comment by eraiza0816** [comment]
同名のユーザ名はやめておきたい（UserIdで管理してるけどUIで表示した際に差が分からないのはう～～んっていう）

**Comment by Sut103** [comment]
まあ、その通り。同名は不可にしましょかね。
それからとりあえず１ユーザ１デバイスな方針ぽいので、パスワードも一旦なくします。

**Comment by Sut103** [comment]
## リクエストの中身
* user_name(ユーザが任意に設定する名前。User.name)
* device_name(アプリで生成されたデバイスごとの固有値。Device.name)
