### ISSUE TITLE
メッセージ投稿APIの作成

### ISSUE THREAD

**Issue by Sut103** [EIMIKI/dropout_s_back#4]
## やること
* メッセージ投稿用のAPIをつくる

### 必要なこと
* アプリからのパラメータをデータベースに登録(Messageテーブル)
  * 投稿ユーザのid
  * タイトル
  * 本文
  * BLEのid
  * 生存期間
* データベースにメッセージと受信者の対応を作成する(Send_messageテーブル)
  * 受信者のid
  * メッセージのid
* 成否を返す

## やりかた
* ルーティングの先にメソッドを書いていく

**Comment by Sut103** [comment]
全員に対してメッセージを残すとSend_messageテーブルのレコードが一気に増えそうだけど大丈夫かな...。

**Comment by Sut103** [comment]
## リクエストの中身
* device_name(アプリで生成されたデバイスごとの固有値。Device.name)
* title(メッセージのタイトル。Message.title)
* body(メッセージの本文。Message.body)
* ble_uuid(BLEビーコンのUUID。Ble.name)
* due(メッセージの有効期限。y-m-d-h-mの形にする。なくてもいい。Message.due)

**Comment by shokkunrf** [comment]
リクエストに受信者のidが不足していた
* to_user(受信者のid。配列。User.id)
でいいですかね？

**Comment by Sut103** [comment]
ほんとだ。
自分と特定の人に送信する場合はそれでよさそう。
でも、全員に送信する時はどうしよう？0を指定したら全員とかはできそうかな。

それと、ここでUser.idを使うということはユーザ検索APIとユーザ登録APIではUser.idを返すようにした方がいいのかな。

**Comment by shokkunrf** [comment]
* to_user(受信者名。配列。User.Name)  
になりました
